# Generated by Django 2.1.3 on 2019-01-24 14:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('insta_app', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_filed',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='like', to='insta_app.Profile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='insta_app.Post'),
        ),
    ]
